# Generated by Django 3.1.7 on 2021-03-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0002_auto_20210306_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='education_type',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_link', models.CharField(max_length=255, null=True, verbose_name='Сайт компании')),
                ('position', models.CharField(max_length=255, verbose_name='Дожность')),
                ('data_from', models.DateField(verbose_name='Дата начала работы')),
                ('data_to', models.DateField(verbose_name='Дата окончания работы')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantapp.resume')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'get_latest_by': '-id',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специальность')),
                ('year_of_ending', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantapp.resume')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
                'get_latest_by': '-id',
            },
        ),
    ]
