# Generated by Django 3.1.7 on 2021-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0003_auto_20210306_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='key_skills',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='links',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на профиль в соц. сетях или сайт'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='moder_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемая заработная плата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user_pic',
            field=models.ImageField(upload_to='media/photo', verbose_name='Фото'),
        ),
    ]
