# Generated by Django 3.1.7 on 2021-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0004_auto_20210306_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_pic',
            field=models.ImageField(upload_to='resume/photo', verbose_name='Фото'),
        ),
    ]
