# Generated by Django 3.1.7 on 2021-03-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0007_auto_20210313_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='applicantapp.statusresume'),
        ),
    ]
