# Generated by Django 3.1.7 on 2021-03-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0008_auto_20210315_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusresume',
            options={'verbose_name': 'Статус Резюме', 'verbose_name_plural': 'Статусы Резюме'},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='resume_id',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='resume_id',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='user',
        ),
    ]
