version: "3"

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=geek_staff
      - POSTGRES_PASSWORD=geek_staff
      - POSTGRES_DB=geek_staff
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    volumes:
      - /opt/staff/static:/opt/app/static
      - /opt/staff/static:/opt/app/media
    environment:
      - DEBUG=False
    entrypoint: ./run.sh
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - /opt/staff/static:/opt/web/static
      - /opt/staff/static:/opt/web/media
    ports:
      - 8888:80
    depends_on:
      - app
    links:
      - app