# Generated by Django 3.1.7 on 2021-03-09 00:58

import companyapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование компании')),
                ('logo', models.ImageField(upload_to=companyapp.models.Company.user_directory_path, verbose_name='Логотип')),
                ('headline', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('detail', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('location', models.CharField(max_length=255, verbose_name='Местонахождение')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на сайт / соц.сеть')),
                ('is_active', models.BooleanField(default=False, verbose_name='Профиль компании активен')),
                ('is_cheked', models.BooleanField(default=False, verbose_name='Проверена модератором')),
                ('moder_comment', models.TextField(verbose_name='Заключение модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name="user's id")),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Вакансия активна')),
                ('is_cheked', models.BooleanField(default=False, verbose_name='Проверена модератором')),
                ('moder_comment', models.TextField(verbose_name='Заключение модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='companyapp.company', verbose_name='ID компании')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-created_at',),
            },
        ),
    ]
