# Generated by Django 3.1.7 on 2021-03-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_cheked',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('0', 'Черновик'), ('1', 'На модерации'), ('2', 'Опубликована')], db_index=True, default='0', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='moder_comment',
            field=models.TextField(null=True, verbose_name='Заключение модератора'),
        ),
    ]
