# Generated by Django 3.1.7 on 2021-04-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сайт / соц.сеть'),
        ),
        migrations.AlterField(
            model_name='company',
            name='moder_comment',
            field=models.TextField(blank=True, verbose_name='Заключение модератора'),
        ),
        migrations.AlterField(
            model_name='job',
            name='moder_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Заключение модератора'),
        ),
    ]
