# Generated by Django 3.1.7 on 2021-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_auto_20210313_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_cheked',
        ),
        migrations.AddField(
            model_name='company',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число просмотров'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('NO', ''), ('FLS', 'Full Stack'), ('FED', 'Front-end'), ('BED', 'Back-end'), ('JVA', 'Java'), ('JST', 'JavaScript'), ('AND', 'Android'), ('IOS', 'iOS'), ('PTN', 'Python'), ('C', 'C')], db_index=True, default='NO', max_length=3, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment',
            field=models.CharField(choices=[('FT', 'Полная занятость'), ('PT', 'Частичная занятость'), ('PW', 'Проектная работа'), ('VL', 'Волонтерство'), ('WP', 'Стажировка')], db_index=True, default='FT', max_length=2, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('WE', 'Без опыта'), ('SM', 'До 1 года'), ('MD', '1-3 года'), ('BG', 'Более 3 лет')], db_index=True, default='WE', max_length=2, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='job',
            name='grade',
            field=models.CharField(choices=[('NO', ''), ('TR', 'Trainee'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('TL', 'TeamLead'), ('TD', 'CTO')], db_index=True, default='NO', max_length=2, verbose_name='Классность'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(default='', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=255, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Отклонена модератором'), ('1', 'Заготовка'), ('2', 'На модерации'), ('3', 'Опубликована'), ('4', 'Черновик'), ('5', 'Скрыта'), ('6', 'Закрыта'), ('9', 'Удалена')], db_index=True, default='1', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число просмотров'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('SSCH', 'Сменный график'), ('FSCH', 'Гибкий график'), ('RW', 'Удаленная работа'), ('RBW', 'Вахтовый метод')], db_index=True, default='FD', max_length=4, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('0', 'Отклонена модератором'), ('1', 'Заготовка'), ('2', 'На модерации'), ('3', 'Опубликована'), ('4', 'Черновик'), ('9', 'Удалена')], db_index=True, default='1', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='job',
            name='moder_comment',
            field=models.TextField(null=True, verbose_name='Заключение модератора'),
        ),
    ]
