# Generated by Django 3.1.7 on 2021-04-14 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyapp', '0002_auto_20210413_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранные вакансии',
                'verbose_name_plural': 'Избранные вакансии',
                'get_latest_by': '-id',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
