# Generated by Django 3.1.7 on 2021-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_auto_20210409_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('FLS', 'Full Stack'), ('FED', 'Front-end'), ('BED', 'Back-end'), ('SW', 'Software'), ('AI', 'AI & ML'), ('BD', 'Big Data'), ('AND', 'Android'), ('IOS', 'iOS'), ('IOT', 'IoT'), ('QA', 'QA Engineer'), ('GD', 'GameDev'), ('PJM', 'Project Manager'), ('PDM', 'Product Manager')], db_index=True, max_length=3, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment',
            field=models.CharField(choices=[('FT', 'Полная занятость'), ('PT', 'Частичная занятость'), ('PW', 'Проектная работа'), ('VL', 'Волонтерство'), ('WP', 'Стажировка')], db_index=True, max_length=2, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('WE', 'Без опыта'), ('SM', 'До 1 года'), ('MD', '1-3 года'), ('BG', 'Более 3 лет')], db_index=True, max_length=2, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='grade',
            field=models.CharField(choices=[('TR', 'Trainee'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('TL', 'TeamLead'), ('TD', 'CTO')], db_index=True, max_length=2, verbose_name='Классность'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('SSCH', 'Сменный график'), ('FSCH', 'Гибкий график'), ('RW', 'Удаленная работа'), ('RBW', 'Вахтовый метод')], db_index=True, max_length=4, verbose_name='График работы'),
        ),
    ]
