# Generated by Django 3.1.7 on 2021-03-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_auto_20210317_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('NO', ''), ('FLS', 'Full Stack'), ('FED', 'Front-end'), ('BED', 'Back-end'), ('SW', 'Software'), ('AI', 'AI & ML'), ('BD', 'Big Data'), ('AND', 'Android'), ('IOS', 'iOS'), ('IOT', 'IoT'), ('QA', 'QA Engineer'), ('GD', 'GameDev'), ('PJM', 'Project Manager'), ('PDM', 'Product Manager')], db_index=True, default='NO', max_length=3, verbose_name='Категория'),
        ),
    ]
