# Generated by Django 3.1.7 on 2021-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_auto_20210313_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='moder_comment',
            field=models.TextField(default='Комментарий: ', verbose_name='Заключение модератора'),
        ),
        migrations.AlterField(
            model_name='job',
            name='moder_comment',
            field=models.TextField(default='Комментарий: ', verbose_name='Заключение модератора'),
        ),
    ]
