# Generated by Django 3.1.7 on 2021-03-14 07:39

import companyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_auto_20210313_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companyapp.models.Company.user_directory_path, verbose_name='Логотип'),
        ),
    ]
