# Generated by Django 3.1.7 on 2021-03-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_auto_20210314_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('status', '-created_at'), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
