# Generated by Django 3.1.7 on 2021-04-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantapp', '0003_auto_20210413_0539'),
        ('companyapp', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprove_hr', models.BooleanField(default=False, verbose_name='Aprove от hr')),
                ('aprove_recrut', models.BooleanField(default=False, verbose_name='Aprove от рекрута')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
                ('recrut_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantapp.resume')),
                ('vacansy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.job')),
            ],
            options={
                'verbose_name': 'Общий отклик',
            },
        ),
        migrations.RemoveField(
            model_name='inviterecrut',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='inviterecrut',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='inviterecrut',
            name='vacansy',
        ),
        migrations.DeleteModel(
            name='InviteHr',
        ),
        migrations.DeleteModel(
            name='InviteRecrut',
        ),
    ]
