# Generated by Django 3.1.7 on 2021-04-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_favoritesresume_favoritesvacancies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritesvacancies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritesvacancies',
            name='job',
        ),
        migrations.RemoveField(
            model_name='favoritesvacancies',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoritesResume',
        ),
        migrations.DeleteModel(
            name='FavoritesVacancies',
        ),
    ]
