# Generated by Django 3.1.7 on 2021-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210414_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullinvite',
            name='status',
            field=models.CharField(choices=[('0', 'Отклонено'), ('1', 'На рассмотрении')], db_index=True, default='1', max_length=1, verbose_name='Статус'),
        ),
    ]
