# Generated by Django 3.1.7 on 2021-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_fullinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullinvite',
            name='status',
            field=models.CharField(choices=[('0', 'Отклонено'), ('1', 'На рассмотрении'), ('2', 'Принято')], db_index=True, default='1', max_length=1, verbose_name='Статус'),
        ),
    ]
